// Enums

Enum UsageEventType {
  NEW_EVENT
  MINT
  INVALIDATE
  RESALE
  SCAN
  CHECK_IN
  CLAIM
}

// Entities

Table Protocol {
  id id
  getDebitedFromSilos bigdecimal
  getHeldInFuelTanks bigdecimal
  getCreditedToDepot bigdecimal
  getMovedToFeeCollector bigdecimal
  averageGetPerMint bigdecimal
  mintCount bigint
  depotBalance bigdecimal
  invalidateCount bigint
  resaleCount bigint
  scanCount bigint
  checkInCount bigint
  claimCount bigint
}

Table ProtocolDay {
  id id
  day int
  getDebitedFromSilos bigdecimal
  getCreditedToDepot bigdecimal
  getMovedToFeeCollector bigdecimal
  averageGetPerMint bigdecimal
  depotBalance bigdecimal
  mintCount bigint
  invalidateCount bigint
  resaleCount bigint
  scanCount bigint
  checkInCount bigint
  claimCount bigint
}


Table Relayer {
  id id
  getDebitedFromSilo bigdecimal
  getHeldInFuelTanks bigdecimal
  getCreditedToDepot bigdecimal
  averageGetPerMint bigdecimal
  siloBalance bigdecimal
  basePrice bigdecimal
  bufferAddress bytes
  mintCount bigint
  invalidateCount bigint
  resaleCount bigint
  checkInCount bigint
  scanCount bigint
  claimCount bigint
  events Event[] [ref: > Event.relayer]
  tickets Ticket[] [ref: > Ticket.relayer]
  relayerDays RelayerDay[] [ref: > RelayerDay.relayer]
  usageEvents UsageEvent[] [ref: > UsageEvent.relayer]
  topUpEvents TopUpEvent[] [ref: > TopUpEvent.relayer]
}

Table RelayerDay {
  id id
  relayer Relayer
  day int
  getDebitedFromSilo bigdecimal
  getCreditedToDepot bigdecimal
  averageGetPerMint bigdecimal
  siloBalance bigdecimal
  basePrice bigdecimal
  mintCount bigint
  invalidateCount bigint
  resaleCount bigint
  checkInCount bigint
  scanCount bigint
  claimCount bigint
}

Table Event {
  id id
  createTx bytes
  relayer Relayer
  usageEvents UsageEvent[] [ref: > UsageEvent.event]
  tickets Ticket[] [ref: > Ticket.event]
  getDebitedFromSilo bigdecimal
  getHeldInFuelTanks bigdecimal
  getCreditedToDepot bigdecimal
  averageGetPerMint bigdecimal
  mintCount bigint
  invalidateCount bigint
  resaleCount bigint
  checkInCount bigint
  scanCount bigint
  claimCount bigint
  eventName string
  shopUrl string
  imageUrl string
  orderTime bigint
  latitude bigdecimal
  longitude bigdecimal
  currency string
  ticketeerName string
  startTime bigint
  endtime bigint
}

Table Ticket {
  id id
  nftIndex bigint
  createTx bytes
  usageEvents UsageEvent[] [ref: > UsageEvent.event]
  event Event
  relayer Relayer
  getDebitedFromSilo bigdecimal
  getHeldInFuelTank bigdecimal
  getCreditedToDepot bigdecimal
}

Table TopUpEvent {
  id id
  txHash bytes
  relayer Relayer
  relayerAddress bytes
  blockNumber bigint
  blockTimestamp bigint
  orderTime bigint
  day int
  amount bigdecimal
  price bigdecimal
}

Table UsageEvent {
  id id
  txHash bytes
  relayer Relayer
  relayerAddress bytes
  blockNumber bigint
  blockTimestamp bigint
  orderTime bigint
  day int
  type UsageEventType
  getDebitedFromSilo bigdecimal
  getCreditedToDepot bigdecimal
  event event
  eventAddress bytes
  ticket Ticket
  nftIndex bigint
  latitude bigdecimal
  longitude bigdecimal
}