name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Prepare subgraph.yaml
        run: yarn prepare:polygon-production && yarn prepare:polygon-production-v1
      - name: Generate types
        run: yarn codegen
      - name: Run linting checks
        run: yarn run check
